name: Kiuwan Delivery Demo

on:
  push:
    branches:
      - main
      - QA
  pull_request:
    branches:
      - main
      - QA

jobs:
  kiuwan-delivery:
    name: "Entrega automatizada en Kiuwan Lifecycle"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout del código"
        uses: actions/checkout@v4

      - name: "Ejecutar Delivery Kiuwan"
        uses: lsacera/KiuwanDeliveryAction@v1.1
        with:
          project: test_demo
          label: "CodeBuild_${{ github.run_number }}"     # Delivery label visible en Kiuwan
          userid: ${{ secrets.KIUWAN_USER }}
          password: ${{ secrets.KIUWAN_PASS }}
          changerequest: "HU-${{ github.run_number }}"    # Relación con la HU o ticket
          branch: ${{ github.ref_name }}                  # Detecta automáticamente la rama (main/QA)
          type: completeDelivery
          status: resolved
