name: Kiuwan Delivery Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kiuwan-delivery:
    name: "Entrega automática en Kiuwan Lifecycle"
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona tu código fuente
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2️⃣ Ejecuta el análisis y genera la entrega
      - name: Ejecutar Delivery en Kiuwan
        uses: lsacera/KiuwanDeliveryAction@v1.1
        with:
          # Nombre del proyecto en Kiuwan (ya existente)
          project: test_demo

          # Etiqueta del análisis (se verá en "Delivery label")
          label: "CodeBuild_${{ github.run_number }}"

          # Credenciales (desde Secrets)
          userid: ${{ secrets.KIUWAN_USER }}
          password: ${{ secrets.KIUWAN_PASS }}

          # Parámetros opcionales (para trazabilidad)
          changerequest: "HU-${{ github.run_number }}"
          branch: "main"
          type: completeDelivery       # o partialDelivery
          status: resolved             # o inprogress

          # Parámetros avanzados (opcional)
          # advancedparams: "--analyzeDependencies --encoding UTF-8"

