name: Kiuwan Demo Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast-kiuwan:
    name: "Ejecutar análisis SAST con Kiuwan"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout del código fuente"
        uses: actions/checkout@v4

      - name: "Descargar Kiuwan Local Analyzer"
        run: |
          wget https://www.kiuwan.com/pub/analyzer/KiuwanLocalAnalyzer.zip
          unzip -q KiuwanLocalAnalyzer.zip

      - name: "Ejecutar análisis con Kiuwan"
        run: |
          ./KiuwanLocalAnalyzer/bin/agent.sh \
          -n "test_demo" \
          -s ./src \
          --label "${{ github.run_number }}" \
          --exitCodes \
          --user "${{ secrets.KIUWAN_USER }}" \
          --pass "${{ secrets.KIUWAN_PASS }}"
